CREATE TABLE IF NOT EXISTS categorias (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
)

CREATE TABLE IF NOT EXISTS fornecedores (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
telefone VARCHAR(30),
email VARCHAR(50),
CONSTRAINT contato_obrigatorio CHECK (telefone IS NOT NULL OR email IS NOT NULL)
)

CREATE TABLE IF NOT EXISTS produtos (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
preco DECIMAL(12,2),
estoque INTEGER DEFAULT 0,
categoria_id INTEGER REFERENCES categorias(id),
fornecedor_id INTEGER REFERENCES fornecedores(id)
)

CREATE TABLE IF NOT EXISTS cargos (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
salario_base DECIMAL(12,2) NOT NULL,
)

CREATE TABLE IF NOT EXISTS funcionarios (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
cpf VARCHAR(50) UNIQUE NOT NULL,
salario_bonus DECIMAL(12,2) DEFAULT 0,
cargo_id INTEGER REFERENCES cargos(id)
)

CREATE TABLE IF NOT EXISTS clientes (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome VARCHAR(50) NOT NULL
)

CREATE TABLE IF NOT EXISTS vendas (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
total DECIMAL(12,2) NOT NULL,
cliente_id INTEGER REFERENCES clientes(id),
funcionarios_id INTEGER REFERENCES funcionarios(id)
)

CREATE TABLE IF NOT EXISTS itens_venda (
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
quantidade INTEGER NOT NULL,
preco_unit DECIMAL(10,2) NOT NULL,
venda_id INTEGER NOT NULL REFERENCES vendas(id),
produto_id INTEGER NOT NULL REFERENCES produtos(id)
)